// types/api.ts is generated by openapi-typescript on every build.
// Wrap with Zod for runtime validation.
import type { paths } from "./types/api";
import { z } from "zod";

const MeResponse = z.object({ id: z.string(), displayName: z.string(), email: z.string().email() });
export type Me = z.infer<typeof MeResponse>;

export async function loadMe(): Promise<Me> {
  return MeResponse.parse(await fetch("/me").then(r => r.json()));
}
